[package]
name = "denoserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.13"
deno_core = "0.145.0"
deno_runtime = "0.71.0"
tokio = { version = "1.20.1", features = ["full"] }
